### ISSUE TITLE
Can binary be made available?

### ISSUE THREAD

**Issue by crsCR** [w3f/substrate-telemetry-exporter#1]
...for those not wanting to use Docker.

Thanks.

**Comment by fgimenez** [comment]
You can do the same as in the Dockerfile, from a clone of that repo you can run `yarn && yarn start`

Closing now, feel free to reopen if that doesn't work.

**Comment by crsCR** [comment]
Running that gives me: 
```
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.19s.
yarn run v1.17.3
$ node src/index.js
Starting the collection of metrics, the metrics are available on /metrics
Could not connect to substrate-telemetry on ws://localhost:8080: Error: connect ECONNREFUSED 127.0.0.1:8080
Conection to substrate-telemetry on ws://localhost:8080 closed
Done in 1.44s.

```

**Comment by fgimenez** [comment]
Yes, the exporter tries to connect to a telemetry backend running on localhost:8080

**Comment by crsCR** [comment]
Ah... OK - I'll investigate further. Thanks.

**Comment by crsCR** [comment]
I guess you don't have to run the telemetry backend on same machine as validator but can target it? If you've set your validator to --no-telemetry, will this work still for your validator metrics?
