### ISSUE TITLE
Unable to retrieve information from Substrate Telemetry backend.

### ISSUE THREAD

**Issue by Mitchell-Grimes** [w3f/substrate-telemetry-exporter#9]
I have working telemetry backend. 
`Telemetry server listening on port 1024
Feed server listening on port 8080
[System] 0 open telemetry connections; 0 open feed connections
[System] 0 open telemetry connections; 0 open feed connections
root@ubuntu-bionic:/usr/local/substrate-telemetry# tail -f /var/log/telemetry.backend.log
[Kusama CC2] Kasuma-01 imported 37292, block time: 0.03s, average: 0.0442s | latency 0
[Kusama CC2] New block 37322
[Kusama CC2] Kasuma-01 imported 37322, block time: 0.033s, average: 0.0361s | latency 0
[Kusama CC2] New block 37352
[Kusama CC2] Kasuma-01 imported 37352, block time: 0.032s, average: 0.0345s | latency 0
[System] 1 open telemetry connections; 1 open feed connections
[Kusama CC2] New block 37382
[Kusama CC2] Kasuma-01 imported 37382, block time: 0.031s, average: 0.0316s | latency 0
[Kusama CC2] New block 37412
[Kusama CC2] Kasuma-01 imported 37412, block time: 0.034s, average: 0.0335s | latency 0
[Kusama CC2] New block 37441
[Kusama CC2] Kasuma-01 imported 37441, block time: 0.033s, average: 0.0363s | latency 0
[Kusama CC2] New block 37471
[Kusama CC2] Kasuma-01 imported 37471, block time: 0.037s, average: 0.0339s | latency 0
[System] 1 open telemetry connections; 1 open feed connections
[Kusama CC2] New block 37499`

But when looking at telemetry exporter, it's just waiting, even after restarting. 
`Telemetry server listening on port 1024
Feed server listening on port 8080
[System] 0 open telemetry connections; 0 open feed connections
[System] 0 open telemetry connections; 0 open feed connections`

This is using master branch of both `substrate-telemetry` and `substrate-telemetry-exporter`

**Comment by akhanaton** [comment]
Same issue here. I was using v0.4.0 and that worked fine.

**Comment by fgimenez** [comment]
Thanks for the report, the default config was updated to subscribe to `kusama cc3`, which finally didn't happen. Already fixed, pls pull and try again.

Also, we need to document the configuration, will be done in #11
